### ISSUE TITLE
Add version numbers for setuptools

### ISSUE THREAD

**Issue by pgarrison** [allen-cell-animated/colorizer-data#50]
# Steps to reproduce
```bash
python -m venv venv
source venv/bin/activate
pip install git+https://github.com/allen-cell-animated/colorizer-data.git@v1.2.0
pip list
```

Expected output:
```
colorizer_data     1.2.0
```

Actual output:
```
colorizer_data     0.0.0
```

# Debugging
The `pyproject.toml` specifies `dynamic = ["version"]`, but the version configuration is missing. The [docs](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata) suggest something like this is necessary.
```toml
[tool.setuptools.dynamic]
version = {attr = "my_package.VERSION"}
```
